inherit_from: .rubocop_todo.yml

# Global options
AllCops:
  DisplayCopNames: true
  NewCops: disable

# While we support 2.4+, it still works with 2.0+
Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/AbcSize:
  Max: 60

Metrics/BlockLength:
  Max: 800

Metrics/CyclomaticComplexity:
  Max: 15

Style/AccessorGrouping:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Layout/LineLength:
  # This will disable the rule completely, regardless what other options you put
  Enabled: true
  # Change the default 80 chars limit value
  Max: 120

Metrics/MethodLength:
  # This cop checks if the length of a method exceeds some maximum value
  Enabled: true
  # Change the default 10 lines limit value
  Max: 50

# Allow classes longer than 100 lines of code
Metrics/ClassLength:
  Max: 250

Naming/MethodParameterName:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false

Metrics/ParameterLists:
  MaxOptionalParameters: 6

Metrics/PerceivedComplexity:
  Max: 11

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantReturn:
  Enabled: false

Style/SafeNavigation:
  Enabled: false
