# Global options
AllCops:
  DisplayCopNames: true

Metrics/LineLength:
  # This will disable the rule completely, regardless what other options you put
  Enabled: true
  # Change the default 80 chars limit value
  Max: 120

# Allow classes longer than 100 lines of code
ClassLength:
  Max: 250
